version: "3.9"
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password

  redis:
    image: redis
    volumes:
      - ./tmp/db/redis:/var/lib/redis/data

  web:
    stdin_open: true
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis

